-- ========================================================
-- NIGAZHTHISAI DATABASE VIEWS (DEPRECATED & DELETED)
-- ========================================================
-- All calculations are now done dynamically in RPCs and code.
